title: "Region Västmanland Blogg"
description: "Officiell blogg för Region Västmanland"
url: "https://region-vastmanland.github.io"
baseurl: "/blog"
show_posts: true
theme: jekyll-theme-minimal

paginate: 6
paginate_path: "/page:num/"

# Sidebar-inställningar
show_sidebar: true
show_categories: true
show_tags: true

collections:
  posts:
    output: true
